@startuml
[*] --> SaveNewPhoto : EventNew\nPhotoReceived
SaveNewPhoto --> ProcessColorModel: EventNew\nPhotoSaved
SaveNewPhoto --> ProcessObjectModel : EventNew\nPhotoSaved
SaveNewPhoto --> ProcessEmotionModel : EventNew\nPhotoSaved

ProcessColorModel --> SaveModelsResult : Event\nColors\nDetermined
ProcessObjectModel --> SaveModelsResult : Event\nObjects\nDetermined
ProcessEmotionModel --> SaveModelsResult : Event\nEmotions\nDetermined

SaveModelsResult --> ProcessAssociationsModel : Event\nEmotionAndObject\nDetermined
SaveModelsResult --> ProcessUniqueness : EventColors\nReadyСount\nUniqueness
SaveModelsResult --> ProcessUniqueness : EventTags\nReadyСount\nUniqueness


ProcessAssociationsModel -right-> SaveModelsResult : Event\nAssociations\nDetermined

ProcessUniqueness --> SaveUniquenessResult : EventColor\nUniqueness\nDetermined
ProcessUniqueness --> SaveUniquenessResult : EventTags\nUniqueness\nDetermined
ProcessUniqueness --> SaveUniquenessResult : EventOverall\nUniqueness\nDetermined

SaveModelsResult -down-> ShowResult : Event\nColors\nRecorded
SaveModelsResult -down-> ShowResult : Event\nObject\nRecorded
SaveModelsResult -down-> ShowResult : Event\nEmotion\nRecorded
SaveModelsResult -down-> ShowResult : Event\nAssociations\nRecorded
SaveUniquenessResult -right-> ShowResult : EventColorslUniquenessRecorded
SaveUniquenessResult -right-> ShowResult : EventTagsUniquenessRecorded
SaveUniquenessResult -right-> ShowResult : EventOverallUniquenessRecorded


@enduml

